stages:
  - build
  - test
  - deploy

build_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build  -f docker/Dockerfile.production -t "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"  .
    - docker push "$QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
    - docker build  -f docker/Dockerfile.production -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"  .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

test:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  services:
    - postgres:9.6
  variables:
    DB_NAME: vframe
    DB_USER: postgres
    DB_PASS: postgres
    DB_HOST: postgres
  tags:
    - meedan
    - meedan-labs
  stage: test
  script:
    - . /opt/conda/etc/profile.d/conda.sh
    - conda activate vframe
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - source configurator/check/test/vframe/.env_file
    - cd api && FLASK_ENV=test DB_NAME=vframe_test coverage run manage.py test

deploy_qa:
  image: python:3-alpine
  stage: deploy
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install ecs-deploy==1.7.0
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - source configurator/check/qa/vframe/.env_file
    - ecs deploy ecs-qa  qa-vframe --image qa-vframe-c $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA -e qa-vframe-c DB_USER $DB_USER -e qa-vframe-c DB_PASS $DB_PASS -e qa-vframe-c DB_HOST $DB_HOST -e qa-vframe-c DB_NAME $DB_NAME --timeout -1
    - echo "new Image was deployed $QA_ECR_API_BASE_URL:$CI_COMMIT_SHA"
  only:
    - develop