version: '3'
networks:
  dev:
    driver: bridge
volumes:
  postgres:
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dev
  vframe:
    build: .
    volumes:
      - ".:/root/vframe"
    environment:
      - "DB_HOST=postgres"
      - "DB_NAME=vframe"
      - "DB_USER=postgres"
      - "DB_PASS=postgres"
      - "FLASK_ENV=development"
      - "FLASK_DEBUG=1"
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - dev
