volumes:
  postgres:
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - dev
  vframe:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.production
    volumes:
      - ".:/root/vframe"
    env_file:
      - .env_file
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - dev
