version: '3'
networks:
  dev:
    driver: bridge
volumes:
  mysql:
services:
  mysql:
    image: mysql:5
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=vframe"
      - "MYSQL_USER=vframe"
      - "MYSQL_PASSWORD=vframe"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - dev
  vframe:
    build: .
    volumes:
      - ".:/root/vframe"
    environment:
      - "DB_HOST=mysql"
      - "DB_NAME=vframe"
      - "DB_USER=vframe"
      - "DB_PASS=vframe"
      - "FLASK_ENV=development"
      - "FLASK_DEBUG=1"
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - dev
