version: '3'
networks:
  dev:
    driver: bridge
volumes:
  mysql:
#  redis:
services:
  mysql:
    image: mysql:5
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=vframe"
      - "MYSQL_USER=vframe"
      - "MYSQL_PASSWORD=vframe"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    networks:
      - dev
#  redis:
#    image: redis:5
#    ports:
#      - "6379:6379"
#    volumes:
#      - "redis:/data"
#    networks:
#      - dev
  vframe:
    build: .
    env_file:
      - .env_file
    depends_on:
      - mysql
#      - redis
    ports:
      - "5000:5000"
    networks:
      - dev
